version: '3.1'
services:
        joomla:
                image: joomla:apache
                ports:
                - 8080:80
                volumes:
                - webdata:/var/www/html
                environment:
                        JOOMLA_DB_HOST: mariadb
                        JOOMLA_DB_NAME: dockerbuch
                        JOOMLA_DB_USER: dockerbuch
                        JOOMLA_DB_PASSWORD: Sml12345
        mariadb:
                image: fst135207/dockerfilev2
                environment:
                        MYSQL_ROOT_PASSWORD: Sml12345
                        MYSQL_DATABASE: dockerbuch
                        MYSQL_USER: dockerbuch
                        MYSQL_PASSWORD: Sml12345
volumes:
        webdata:
